import { useEffect, useState } from 'react'
import { Ban, CircleDollarSign, ReceiptText, Trash2, UserRound, UsersRound, WalletCards } from 'lucide-react'
import { Navigate } from 'react-router-dom'
import { api, errorMessage } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import { Card, LoadingScreen, PageHeader, Toast } from '../components/UI'
import { niceDate } from '../lib/format'

export default function AdminPage(){
  const {user}=useAuth();const [stats,setStats]=useState(null);const [users,setUsers]=useState([]);const [notice,setNotice]=useState(null)
  const load=()=>Promise.all([api.get('/admin/stats'),api.get('/admin/users')]).then(([s,u])=>{setStats(s.data);setUsers(u.data)}).catch(e=>setNotice({message:errorMessage(e),type:'error'}));useEffect(()=>{if(user.role==='ADMIN')load()},[user.role])
  if(user.role!=='ADMIN')return <Navigate to="/" replace/>;if(!stats)return <LoadingScreen/>
  const toggle=async(item)=>{try{await api.patch(`/admin/users/${item.id}/status`,{status:item.status==='active'?'disabled':'active'});await load()}catch(e){setNotice({message:errorMessage(e),type:'error'})}}
  const remove=async(item)=>{if(!window.confirm(`Delete ${item.name}'s account and financial data?`))return;try{await api.delete(`/admin/users/${item.id}`);await load()}catch(e){setNotice({message:errorMessage(e),type:'error'})}}
  const cards=[['Users',stats.users,UsersRound],['Accounts',stats.accounts,WalletCards],['Income entries',stats.incomeRecords,CircleDollarSign],['Expense entries',stats.expenseRecords,ReceiptText]]
  return <div className="fade-in"><PageHeader eyebrow="System control" title="Admin workspace" description="Manage accounts and monitor high-level platform activity without exposing private financial details."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon])=><Card key={label} className="p-5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-500/10"><Icon size={17}/></span><p className="mt-4 text-xs text-slate-400">{label}</p><strong className="mt-1 block text-2xl dark:text-white">{value}</strong></Card>)}</div><Card className="mt-5 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h2 className="text-sm font-bold dark:text-white">User management</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400 dark:bg-slate-900/40"><th className="px-5 py-3">User</th><th className="px-4">Role</th><th className="px-4">Status</th><th className="px-4">Joined</th><th className="px-5 text-right">Actions</th></tr></thead><tbody>{users.map(item=><tr key={item.id} className="border-t border-slate-100 text-xs dark:border-slate-800"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100 text-slate-500 dark:bg-slate-800"><UserRound size={16}/></span><div><p className="font-semibold dark:text-white">{item.name}</p><p className="text-[10px] text-slate-400">{item.email}</p></div></div></td><td className="px-4 text-slate-500">{item.role}</td><td className="px-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${item.status==='active'?'bg-emerald-50 text-emerald-600':'bg-red-50 text-red-500'}`}>{item.status}</span></td><td className="px-4 text-slate-500">{niceDate(item.joined)}</td><td className="px-5"><div className="flex justify-end gap-1"><button className="icon-button h-8 w-8" title="Toggle status" onClick={()=>toggle(item)}><Ban size={14}/></button><button className="icon-button h-8 w-8 hover:text-red-500" title="Delete" onClick={()=>remove(item)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div></Card><Toast {...notice} onClose={()=>setNotice(null)}/></div>
}
