import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowRight, ArrowUpRight, CalendarDays, ChevronRight, CircleDollarSign, CreditCard, Landmark, PiggyBank, ReceiptText, Sparkles, WalletCards } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api, errorMessage } from '../lib/api'
import { money, niceDate } from '../lib/format'
import { Card, LoadingScreen, Progress } from '../components/UI'
import { DonutChart, TrendChart } from '../components/Charts'
import { useAuth } from '../context/AuthContext'

const statConfig = [
  { key:'income', label:'Total income', icon:CircleDollarSign, color:'text-emerald-600 bg-emerald-50 dark:bg-emerald-500/10', note:'this month' },
  { key:'expenses', label:'Total expenses', icon:ReceiptText, color:'text-red-500 bg-red-50 dark:bg-red-500/10', note:'this month' },
  { key:'net', label:'Net savings', icon:PiggyBank, color:'text-blue-600 bg-blue-50 dark:bg-blue-500/10', note:'income minus expenses' },
  { key:'accountBalance', label:'Total balance', icon:WalletCards, color:'text-violet-600 bg-violet-50 dark:bg-violet-500/10', note:'across all accounts' },
]

export default function DashboardPage() {
  const { user } = useAuth(); const [data,setData]=useState(null); const [error,setError]=useState('')
  useEffect(()=>{ api.get('/dashboard').then(r=>setData(r.data)).catch(e=>setError(errorMessage(e))) },[])
  if (!data && !error) return <LoadingScreen/>
  if (error) return <Card className="p-8 text-center text-sm text-red-500">{error}</Card>
  const period = new Intl.DateTimeFormat('en-PH',{month:'long',year:'numeric'}).format(new Date())
  return <div className="fade-in">
    <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 flex items-center gap-1.5 text-xs font-semibold text-blue-600 dark:text-blue-400"><Sparkles size={13}/> Financial overview</p><h1 className="text-2xl font-bold tracking-[-.035em] text-slate-900 dark:text-white sm:text-[28px]">Good day, {user?.firstName}</h1><p className="mt-1.5 text-sm text-slate-500">Here’s how your money is moving this month.</p></div><span className="inline-flex h-10 items-center gap-2 self-start rounded-xl border border-slate-200 bg-white px-3.5 text-xs font-semibold text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300"><CalendarDays size={15}/>{period}</span></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{statConfig.map(({key,label,icon:Icon,color,note})=><Card key={key} className="group p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${color}`}><Icon size={19}/></span>{key==='expenses' && <span className={`flex items-center gap-1 text-[11px] font-semibold ${Number(data.expenseChange)>0?'text-red-500':'text-emerald-500'}`}>{Number(data.expenseChange)>0?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {Math.abs(Number(data.expenseChange))}%</span>}</div><p className="mt-5 text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold tracking-[-.04em] text-slate-900 dark:text-white">{money(data[key])}</p><p className="mt-1 text-[11px] text-slate-400">{note}</p></Card>)}</div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.55fr_1fr]">
      <Card className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-sm font-bold text-slate-900 dark:text-white">Cash flow</h2><p className="mt-1 text-xs text-slate-400">Income versus expenses over 6 months</p></div><div className="flex gap-3 text-[11px]"><span className="flex items-center gap-1.5 text-slate-500"><i className="h-2 w-2 rounded-full bg-emerald-500"/>Income</span><span className="flex items-center gap-1.5 text-slate-500"><i className="h-2 w-2 rounded-full bg-red-500"/>Expenses</span></div></div><div className="mt-3"><TrendChart data={data.trend}/></div></Card>
      <Card className="p-5 sm:p-6"><div className="mb-6 flex items-start justify-between"><div><h2 className="text-sm font-bold text-slate-900 dark:text-white">Spending breakdown</h2><p className="mt-1 text-xs text-slate-400">Where your money went</p></div><Link to="/reports" className="text-xs font-semibold text-blue-600">Details</Link></div><DonutChart data={data.categoryBreakdown}/></Card>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_1fr]">
      <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 dark:border-slate-800"><div><h2 className="text-sm font-bold text-slate-900 dark:text-white">Recent activity</h2><p className="mt-0.5 text-[11px] text-slate-400">Latest income and expenses</p></div><Link to="/expenses" className="flex items-center gap-1 text-xs font-semibold text-blue-600">View all<ChevronRight size={14}/></Link></div><div>{data.recentTransactions?.map((item)=><div key={item.id} className="flex items-center gap-3 border-b border-slate-100 px-5 py-3.5 last:border-0 dark:border-slate-800"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${item.type==='income'?'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10':'bg-slate-100 text-slate-500 dark:bg-slate-800'}`}>{item.type==='income'?<ArrowDownRight size={17}/>:<ArrowUpRight size={17}/>}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-800 dark:text-slate-100">{item.name}</p><p className="mt-0.5 text-[10px] text-slate-400">{item.category} · {niceDate(item.date)}</p></div><strong className={`text-xs ${item.type==='income'?'text-emerald-600':'text-slate-800 dark:text-white'}`}>{item.type==='income'?'+':'−'}{money(item.amount)}</strong></div>)}</div></Card>
      <div className="grid gap-4">
        <Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-bold dark:text-white">Budget pulse</h2><p className="mt-0.5 text-[11px] text-slate-400">Monthly limits</p></div><Link to="/budgets" className="text-xs font-semibold text-blue-600">Manage</Link></div><div className="space-y-4">{data.budgets?.slice(0,4).map((b)=><div key={b.id}><div className="mb-1.5 flex justify-between text-[11px]"><span className="font-semibold text-slate-600 dark:text-slate-300">{b.category.name}</span><span className={Number(b.percentage)>100?'font-semibold text-red-500':'text-slate-400'}>{Math.round(b.percentage)}%</span></div><Progress value={b.percentage} color={Number(b.percentage)>100?'#EB5757':b.category.color}/></div>)}</div></Card>
        <Card className="overflow-hidden"><div className="flex items-center justify-between px-5 pt-5"><div><h2 className="text-sm font-bold dark:text-white">Your accounts</h2><p className="mt-0.5 text-[11px] text-slate-400">Available balances</p></div><Link to="/accounts"><ArrowRight size={16} className="text-blue-500"/></Link></div><div className="mt-3">{data.accounts?.filter(a=>a.active).slice(0,3).map((a)=><div key={a.id} className="flex items-center gap-3 px-5 py-2.5"><span className="flex h-8 w-8 items-center justify-center rounded-lg" style={{background:`${a.color}18`,color:a.color}}>{a.type==='BANK'?<Landmark size={15}/>:<WalletCards size={15}/>}</span><p className="flex-1 text-xs font-semibold text-slate-600 dark:text-slate-300">{a.name}</p><strong className="text-xs dark:text-white">{money(a.balance,a.currency)}</strong></div>)}</div></Card>
      </div>
    </div>
    {data.upcomingSubscriptions?.length>0 && <Card className="mt-4 flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-violet-600 dark:bg-violet-500/10"><CreditCard size={19}/></span><div className="flex-1"><p className="text-sm font-bold dark:text-white">Upcoming subscriptions</p><p className="mt-0.5 text-xs text-slate-400">{data.upcomingSubscriptions[0].name} is due {niceDate(data.upcomingSubscriptions[0].nextBillingDate)} · {money(data.upcomingSubscriptions[0].amount)}</p></div><Link to="/subscriptions" className="btn-secondary">Review bills<ArrowRight size={15}/></Link></Card>}
  </div>
}
