import { useCallback, useEffect, useState } from 'react'
import { useLocation } from 'react-router-dom'
import {
  ArrowDownLeft, ArrowRight, ArrowRightLeft, ArrowUpRight, CalendarClock, CheckCircle2,
  CreditCard, Edit3, Goal, Landmark, PiggyBank, ReceiptText,
  Search, Trash2, Wallet, WalletCards,
} from 'lucide-react'
import { api, errorMessage } from '../lib/api'
import { currentMonth, money, niceDate, today } from '../lib/format'
import { Button, Card, EmptyState, Field, FormActions, LoadingScreen, Modal, PageHeader, Progress, Select, Textarea, Toast } from '../components/UI'

function useCrud(endpoint) {
  const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(null)
  const load=useCallback(()=>{setLoading(true);return api.get(endpoint).then(r=>setItems(r.data)).catch(e=>setNotice({message:errorMessage(e),type:'error'})).finally(()=>setLoading(false))},[endpoint])
  useEffect(()=>{load()},[load])
  const save=async(id,payload)=>{setSaving(true);try{await api[id?'put':'post'](`${endpoint}${id?`/${id}`:''}`,payload);setNotice({message:`Saved successfully.`});await load();return true}catch(e){setNotice({message:errorMessage(e),type:'error'});return false}finally{setSaving(false)}}
  const remove=async(id)=>{if(!window.confirm('Delete this item? This cannot be undone.'))return;try{await api.delete(`${endpoint}/${id}`);setNotice({message:'Removed successfully.'});await load()}catch(e){setNotice({message:errorMessage(e),type:'error'})}}
  return {items,loading,saving,notice,setNotice,save,remove,load}
}

function useOptions() {
  const [options,setOptions]=useState({accounts:[],categories:[]})
  useEffect(()=>{Promise.all([api.get('/accounts'),api.get('/categories')]).then(([a,c])=>setOptions({accounts:a.data.filter(x=>x.active),categories:c.data})).catch(()=>{})},[])
  return options
}

const incomeEmpty={source:'',amount:'',date:today(),frequency:'ONE_TIME',categoryId:'',accountId:'',notes:''}
const expenseEmpty={merchant:'',amount:'',date:today(),paymentMethod:'CARD',categoryId:'',accountId:'',notes:'',tags:''}
const subscriptionEmpty={name:'',amount:'',billingCycle:'MONTHLY',nextBillingDate:today(),status:'ACTIVE',categoryId:'',accountId:''}
const goalEmpty={name:'',targetAmount:'',currentAmount:'0',deadline:'',color:'#27AE60',status:'ACTIVE'}

function TransactionPage({type}) {
  const income=type==='income'; const endpoint=income?'/incomes':'/expenses'; const crud=useCrud(endpoint); const {accounts,categories}=useOptions(); const location=useLocation()
  const [open,setOpen]=useState(false); const [editing,setEditing]=useState(null); const [form,setForm]=useState(income?incomeEmpty:expenseEmpty); const [query,setQuery]=useState('')
  useEffect(()=>{if(new URLSearchParams(location.search).get('new')){setEditing(null);setForm(income?incomeEmpty:expenseEmpty);setOpen(true)}},[location.search,income])
  const start=(item)=>{setEditing(item||null);setForm(item?(income?{source:item.source,amount:item.amount,date:item.date,frequency:item.frequency,categoryId:item.category?.id||'',accountId:item.account?.id||'',notes:item.notes||''}:{merchant:item.merchant,amount:item.amount,date:item.date,paymentMethod:item.paymentMethod,categoryId:item.category?.id||'',accountId:item.account?.id||'',notes:item.notes||'',tags:item.tags||''}):(income?incomeEmpty:expenseEmpty));setOpen(true)}
  const submit=async(e)=>{e.preventDefault();const payload={...form,amount:Number(form.amount),categoryId:form.categoryId?Number(form.categoryId):null,accountId:form.accountId?Number(form.accountId):null};if(await crud.save(editing?.id,payload))setOpen(false)}
  const filtered=crud.items.filter(i=>(income?i.source:i.merchant).toLowerCase().includes(query.toLowerCase())||i.category?.name?.toLowerCase().includes(query.toLowerCase()))
  const total=crud.items.reduce((s,i)=>s+Number(i.amount),0)
  if(crud.loading)return <LoadingScreen/>
  return <div className="fade-in"><PageHeader eyebrow="Money in motion" title={income?'Income tracker':'Expense tracker'} description={income?'Keep every source of income organized and connected to the right account.':'Capture daily spending and understand the habits behind it.'} action={()=>start()} actionLabel={income?'Add income':'Add expense'}/>
    <div className="mb-4 grid gap-4 sm:grid-cols-3"><Card className="p-5 sm:col-span-2"><p className="text-xs font-medium text-slate-400">{income?'Income recorded':'Expenses recorded'}</p><div className="mt-2 flex items-end gap-3"><strong className={`text-3xl tracking-[-.04em] ${income?'text-emerald-600':'text-red-500'}`}>{money(total)}</strong><span className="mb-1 text-xs text-slate-400">{crud.items.length} transactions</span></div></Card><Card className="flex items-center gap-3 p-5"><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${income?'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10':'bg-red-50 text-red-500 dark:bg-red-500/10'}`}>{income?<ArrowDownLeft size={19}/>:<ArrowUpRight size={19}/>}</span><div><p className="text-xs text-slate-400">Average entry</p><p className="mt-1 text-sm font-bold dark:text-white">{money(crud.items.length?total/crud.items.length:0)}</p></div></Card></div>
    <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-sm font-bold dark:text-white">All {income?'income':'expenses'}</h2><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input h-9 w-full pl-9 sm:w-64" placeholder="Search records..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
      {filtered.length===0?<EmptyState icon={income?Wallet:ReceiptText} title={`No ${income?'income':'expenses'} yet`} message="Add your first record to start building a useful financial picture." action={()=>start()}/>:<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="bg-slate-50/70 text-[10px] uppercase tracking-wider text-slate-400 dark:bg-slate-900/40"><th className="px-5 py-3 font-semibold">{income?'Source':'Merchant'}</th><th className="px-4 py-3 font-semibold">Category</th><th className="px-4 py-3 font-semibold">Account</th><th className="px-4 py-3 font-semibold">Date</th><th className="px-4 py-3 text-right font-semibold">Amount</th><th className="w-24 px-5 py-3"/></tr></thead><tbody>{filtered.map(item=><tr key={item.id} className="group border-t border-slate-100 text-xs dark:border-slate-800"><td className="px-5 py-3.5"><div className="flex items-center gap-3"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${income?'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10':'bg-slate-100 text-slate-500 dark:bg-slate-800'}`}>{income?<ArrowDownLeft size={16}/>:<ReceiptText size={16}/>}</span><div><p className="font-semibold text-slate-800 dark:text-slate-100">{income?item.source:item.merchant}</p><p className="mt-0.5 text-[10px] text-slate-400">{income?item.frequency:item.paymentMethod}</p></div></div></td><td className="px-4 py-3.5"><span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300"><i className="h-1.5 w-1.5 rounded-full" style={{background:item.category?.color||'#94a3b8'}}/>{item.category?.name||'Uncategorized'}</span></td><td className="px-4 text-slate-500 dark:text-slate-400">{item.account?.name||'—'}</td><td className="px-4 text-slate-500 dark:text-slate-400">{niceDate(item.date)}</td><td className={`px-4 text-right font-bold ${income?'text-emerald-600':'text-slate-800 dark:text-white'}`}>{income?'+':'−'}{money(item.amount)}</td><td className="px-5"><div className="flex justify-end opacity-60 group-hover:opacity-100"><button className="icon-button h-8 w-8" onClick={()=>start(item)}><Edit3 size={14}/></button><button className="icon-button h-8 w-8 hover:text-red-500" onClick={()=>crud.remove(item.id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div>}
    </Card>
    <Modal open={open} onClose={()=>setOpen(false)} title={`${editing?'Edit':'Add'} ${income?'income':'expense'}`} description="Keep the details tidy now; your reports will thank you later."><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field className="sm:col-span-2" label={income?'Income source':'Merchant name'} required value={income?form.source:form.merchant} onChange={e=>setForm({...form,[income?'source':'merchant']:e.target.value})} placeholder={income?'e.g. Monthly salary':'e.g. Grocery store'}/><Field label="Amount" type="number" min="0.01" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Field label="Date" type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><Select label="Category" value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Uncategorized</option>{categories.filter(c=>c.type===(income?'INCOME':'EXPENSE')).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select label="Account" value={form.accountId} onChange={e=>setForm({...form,accountId:e.target.value})}><option value="">No account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select>{income?<Select label="Frequency" value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="ONE_TIME">One-time</option><option value="WEEKLY">Weekly</option><option value="MONTHLY">Monthly</option><option value="YEARLY">Yearly</option></Select>:<><Select label="Payment method" value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}><option value="CARD">Card</option><option value="CASH">Cash</option><option value="E_WALLET">E-wallet</option><option value="BANK_TRANSFER">Bank transfer</option></Select><Field label="Tags" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="work, essential"/></>}<Textarea className="sm:col-span-2" label="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><div className="sm:col-span-2"><FormActions onCancel={()=>setOpen(false)} saving={crud.saving} label={editing?'Save changes':`Add ${income?'income':'expense'}`}/></div></form></Modal><Toast {...crud.notice} onClose={()=>crud.setNotice(null)}/>
  </div>
}

export function IncomePage(){return <TransactionPage type="income"/>}
export function ExpensesPage(){return <TransactionPage type="expense"/>}

export function BudgetsPage(){
  const crud=useCrud('/budgets');const {categories}=useOptions();const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState({categoryId:'',month:currentMonth(),limitAmount:''})
  const start=(item)=>{setEditing(item||null);setForm(item?{categoryId:item.category.id,month:item.month,limitAmount:item.limitAmount}:{categoryId:'',month:currentMonth(),limitAmount:''});setOpen(true)}
  const submit=async(e)=>{e.preventDefault();if(await crud.save(editing?.id,{...form,categoryId:Number(form.categoryId),limitAmount:Number(form.limitAmount)}))setOpen(false)}
  const total=crud.items.reduce((s,b)=>s+Number(b.limitAmount),0),spent=crud.items.reduce((s,b)=>s+Number(b.spent),0)
  if(crud.loading)return <LoadingScreen/>
  return <div className="fade-in"><PageHeader eyebrow="Monthly guardrails" title="Budget planner" description="Give every category a thoughtful limit, then see how the month is unfolding." action={()=>start()} actionLabel="Create budget"/>
    <Card className="mb-5 overflow-hidden bg-gradient-to-r from-[#17346d] to-[#2F80ED] p-6 text-white sm:p-7"><div className="grid gap-6 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-xs font-semibold text-blue-100/70">Overall monthly budget</p><div className="mt-2 flex flex-wrap items-baseline gap-2"><strong className="text-3xl tracking-[-.04em]">{money(spent)}</strong><span className="text-sm text-blue-100/60">of {money(total)} spent</span></div><Progress value={total?spent/total*100:0} color="white" className="mt-5 bg-white/20"/></div><div className="rounded-2xl bg-white/10 px-6 py-4 text-center backdrop-blur"><p className="text-[11px] text-blue-100/60">Remaining</p><strong className="mt-1 block text-xl">{money(total-spent)}</strong></div></div></Card>
    {crud.items.length===0?<Card><EmptyState icon={PiggyBank} title="Build your first budget" message="Set category limits and your progress will appear here." action={()=>start()} actionLabel="Create budget"/></Card>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{crud.items.map(b=>{const over=Number(b.percentage)>100;return <Card key={b.id} className="group p-5"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl" style={{background:`${b.category.color}16`,color:b.category.color}}><PiggyBank size={18}/></span><div className="flex"><button className="icon-button h-8 w-8" onClick={()=>start(b)}><Edit3 size={14}/></button><button className="icon-button h-8 w-8 hover:text-red-500" onClick={()=>crud.remove(b.id)}><Trash2 size={14}/></button></div></div><div className="mt-5 flex items-end justify-between"><div><h3 className="text-sm font-bold dark:text-white">{b.category.name}</h3><p className="mt-1 text-xs text-slate-400">{money(b.spent)} of {money(b.limitAmount)}</p></div><span className={`text-sm font-bold ${over?'text-red-500':'text-slate-700 dark:text-slate-200'}`}>{Math.round(b.percentage)}%</span></div><Progress className="mt-4" value={b.percentage} color={over?'#EB5757':b.category.color}/><p className={`mt-3 text-[11px] ${over?'text-red-500':'text-slate-400'}`}>{over?`${money(Math.abs(b.remaining))} over budget`:`${money(b.remaining)} remaining`}</p></Card>})}</div>}
    <Modal open={open} onClose={()=>setOpen(false)} title={`${editing?'Edit':'Create'} budget`}><form onSubmit={submit} className="space-y-4"><Select label="Expense category" required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Choose a category</option>{categories.filter(c=>c.type==='EXPENSE').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Field label="Monthly limit" type="number" step="0.01" min="0.01" required value={form.limitAmount} onChange={e=>setForm({...form,limitAmount:e.target.value})}/><Field label="Budget month" type="date" required value={form.month} onChange={e=>setForm({...form,month:e.target.value})} hint="Any date in the month works; it will be normalized automatically."/><FormActions onCancel={()=>setOpen(false)} saving={crud.saving}/></form></Modal><Toast {...crud.notice} onClose={()=>crud.setNotice(null)}/>
  </div>
}

export function SubscriptionsPage(){
  const crud=useCrud('/subscriptions');const {accounts,categories}=useOptions();const location=useLocation();const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState(subscriptionEmpty)
  useEffect(()=>{if(new URLSearchParams(location.search).get('new')){setEditing(null);setForm(subscriptionEmpty);setOpen(true)}},[location.search])
  const start=(item)=>{setEditing(item||null);setForm(item?{name:item.name,amount:item.amount,billingCycle:item.billingCycle,nextBillingDate:item.nextBillingDate,status:item.status,categoryId:item.category?.id||'',accountId:item.account?.id||''}:subscriptionEmpty);setOpen(true)}
  const submit=async(e)=>{e.preventDefault();if(await crud.save(editing?.id,{...form,amount:Number(form.amount),categoryId:form.categoryId?Number(form.categoryId):null,accountId:form.accountId?Number(form.accountId):null}))setOpen(false)}
  const monthly=crud.items.filter(s=>s.status==='ACTIVE').reduce((sum,s)=>sum+Number(s.amount)*(s.billingCycle==='YEARLY'?1/12:s.billingCycle==='WEEKLY'?4.33:1),0)
  if(crud.loading)return <LoadingScreen/>
  return <div className="fade-in"><PageHeader eyebrow="Recurring payments" title="Subscriptions" description="Keep renewals visible, predictable, and easy to trim when priorities change." action={()=>start()} actionLabel="Add subscription"/>
    <div className="mb-5 grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-xs text-slate-400">Estimated monthly cost</p><strong className="mt-2 block text-2xl tracking-[-.04em] dark:text-white">{money(monthly)}</strong></Card><Card className="p-5"><p className="text-xs text-slate-400">Active services</p><strong className="mt-2 block text-2xl tracking-[-.04em] dark:text-white">{crud.items.filter(s=>s.status==='ACTIVE').length}</strong></Card><Card className="p-5"><p className="text-xs text-slate-400">Annual run rate</p><strong className="mt-2 block text-2xl tracking-[-.04em] text-violet-600">{money(monthly*12)}</strong></Card></div>
    {crud.items.length===0?<Card><EmptyState icon={CreditCard} title="No recurring payments" message="Add rent, utilities, streaming, and anything else that renews." action={()=>start()}/></Card>:<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400 dark:bg-slate-900/40"><th className="px-5 py-3">Service</th><th className="px-4 py-3">Billing cycle</th><th className="px-4 py-3">Next bill</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Cost</th><th className="w-24 px-5"/></tr></thead><tbody>{crud.items.map((s,i)=><tr key={s.id} className="group border-t border-slate-100 text-xs dark:border-slate-800"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-xl text-white ${['bg-red-500','bg-emerald-500','bg-violet-500','bg-blue-500'][i%4]}`}><CreditCard size={17}/></span><div><p className="font-semibold dark:text-white">{s.name}</p><p className="mt-0.5 text-[10px] text-slate-400">{s.account?.name||'No account'}</p></div></div></td><td className="px-4 text-slate-500">{s.billingCycle.replace('_',' ')}</td><td className="px-4"><span className="flex items-center gap-1.5 text-slate-500"><CalendarClock size={14}/>{niceDate(s.nextBillingDate)}</span></td><td className="px-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${s.status==='ACTIVE'?'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10':'bg-slate-100 text-slate-500 dark:bg-slate-800'}`}>{s.status}</span></td><td className="px-4 text-right font-bold dark:text-white">{money(s.amount)}</td><td className="px-5"><div className="flex"><button className="icon-button h-8 w-8" onClick={()=>start(s)}><Edit3 size={14}/></button><button className="icon-button h-8 w-8 hover:text-red-500" onClick={()=>crud.remove(s.id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table></div></Card>}
    <Modal open={open} onClose={()=>setOpen(false)} title={`${editing?'Edit':'Add'} subscription`}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field className="sm:col-span-2" label="Service or bill name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Netflix, rent, internet"/><Field label="Amount" type="number" min="0.01" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Field label="Next billing date" type="date" required value={form.nextBillingDate} onChange={e=>setForm({...form,nextBillingDate:e.target.value})}/><Select label="Billing cycle" value={form.billingCycle} onChange={e=>setForm({...form,billingCycle:e.target.value})}><option value="WEEKLY">Weekly</option><option value="MONTHLY">Monthly</option><option value="YEARLY">Yearly</option></Select><Select label="Status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></Select><Select label="Category" value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Uncategorized</option>{categories.filter(c=>c.type==='EXPENSE').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select label="Payment account" value={form.accountId} onChange={e=>setForm({...form,accountId:e.target.value})}><option value="">No account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select><div className="sm:col-span-2"><FormActions onCancel={()=>setOpen(false)} saving={crud.saving}/></div></form></Modal><Toast {...crud.notice} onClose={()=>crud.setNotice(null)}/>
  </div>
}

export function GoalsPage(){
  const crud=useCrud('/goals');const location=useLocation();const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState(goalEmpty)
  useEffect(()=>{if(new URLSearchParams(location.search).get('new')){setEditing(null);setForm(goalEmpty);setOpen(true)}},[location.search])
  const start=(item)=>{setEditing(item||null);setForm(item?{name:item.name,targetAmount:item.targetAmount,currentAmount:item.currentAmount,deadline:item.deadline||'',color:item.color,status:item.status}:goalEmpty);setOpen(true)}
  const submit=async(e)=>{e.preventDefault();if(await crud.save(editing?.id,{...form,targetAmount:Number(form.targetAmount),currentAmount:Number(form.currentAmount),deadline:form.deadline||null}))setOpen(false)}
  const target=crud.items.reduce((s,g)=>s+Number(g.targetAmount),0),saved=crud.items.reduce((s,g)=>s+Number(g.currentAmount),0)
  if(crud.loading)return <LoadingScreen/>
  return <div className="fade-in"><PageHeader eyebrow="Future you fund" title="Financial goals" description="Turn big plans into visible, motivating progress—one contribution at a time." action={()=>start()} actionLabel="Create goal"/>
    <Card className="mb-5 p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-xs text-slate-400">Progress across all goals</p><p className="mt-2 text-2xl font-bold tracking-[-.04em] dark:text-white">{money(saved)} <span className="text-sm font-medium text-slate-400">of {money(target)}</span></p></div><div className="w-full sm:max-w-md"><div className="mb-2 flex justify-between text-[11px] text-slate-400"><span>Overall completion</span><strong className="text-blue-600">{target?Math.round(saved/target*100):0}%</strong></div><Progress value={target?saved/target*100:0}/></div></div></Card>
    {crud.items.length===0?<Card><EmptyState icon={Goal} title="What are you saving for?" message="Create a goal and make the next milestone feel much closer." action={()=>start()} actionLabel="Create goal"/></Card>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{crud.items.map(g=><Card key={g.id} className="group overflow-hidden"><div className="h-1.5" style={{background:g.color}}/><div className="p-5"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-2xl" style={{background:`${g.color}16`,color:g.color}}><Goal size={20}/></span><div className="flex"><button className="icon-button h-8 w-8" onClick={()=>start(g)}><Edit3 size={14}/></button><button className="icon-button h-8 w-8 hover:text-red-500" onClick={()=>crud.remove(g.id)}><Trash2 size={14}/></button></div></div><h3 className="mt-5 text-base font-bold dark:text-white">{g.name}</h3><p className="mt-1 text-xs text-slate-400">Target by {niceDate(g.deadline)}</p><div className="mt-5 flex items-end justify-between"><strong className="text-lg dark:text-white">{money(g.currentAmount)}</strong><span className="text-xs font-bold" style={{color:g.color}}>{Math.round(g.percentage)}%</span></div><Progress className="mt-2.5" value={g.percentage} color={g.color}/><p className="mt-3 text-[11px] text-slate-400">{money(Number(g.targetAmount)-Number(g.currentAmount))} to go</p></div></Card>)}</div>}
    <Modal open={open} onClose={()=>setOpen(false)} title={`${editing?'Update':'Create'} financial goal`}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field className="sm:col-span-2" label="Goal name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Emergency fund"/><Field label="Target amount" type="number" min="0.01" step="0.01" required value={form.targetAmount} onChange={e=>setForm({...form,targetAmount:e.target.value})}/><Field label="Saved so far" type="number" min="0" step="0.01" required value={form.currentAmount} onChange={e=>setForm({...form,currentAmount:e.target.value})}/><Field label="Target date" type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/><Select label="Status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="ACTIVE">Active</option><option value="COMPLETED">Completed</option><option value="PAUSED">Paused</option></Select><label className="block sm:col-span-2"><span className="label">Goal color</span><input type="color" className="h-11 w-full rounded-xl border border-slate-200 bg-white p-1.5 dark:border-slate-700 dark:bg-slate-900" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><div className="sm:col-span-2"><FormActions onCancel={()=>setOpen(false)} saving={crud.saving}/></div></form></Modal><Toast {...crud.notice} onClose={()=>crud.setNotice(null)}/>
  </div>
}

export function AccountsPage(){
  const crud=useCrud('/accounts');const location=useLocation();const [transfers,setTransfers]=useState([]);const [open,setOpen]=useState(false);const [transferOpen,setTransferOpen]=useState(false);const [editing,setEditing]=useState(null);const empty={name:'',type:'BANK',balance:'',currency:'PHP',color:'#2F80ED',active:true};const [form,setForm]=useState(empty);const [transfer,setTransfer]=useState({sourceAccountId:'',destinationAccountId:'',amount:'',transferredAt:'',notes:''});const [moving,setMoving]=useState(false)
  const loadTransfers=()=>api.get('/transfers').then(r=>setTransfers(r.data)).catch(()=>{});useEffect(()=>{loadTransfers()},[]);useEffect(()=>{if(new URLSearchParams(location.search).get('transfer'))setTransferOpen(true)},[location.search])
  const start=(item)=>{setEditing(item||null);setForm(item?{name:item.name,type:item.type,balance:item.balance,currency:item.currency,color:item.color,active:item.active}:empty);setOpen(true)}
  const submit=async(e)=>{e.preventDefault();if(await crud.save(editing?.id,{...form,balance:Number(form.balance)}))setOpen(false)}
  const submitTransfer=async(e)=>{e.preventDefault();setMoving(true);try{await api.post('/transfers',{sourceAccountId:Number(transfer.sourceAccountId),destinationAccountId:Number(transfer.destinationAccountId),amount:Number(transfer.amount),transferredAt:transfer.transferredAt||null,notes:transfer.notes});setTransferOpen(false);setTransfer({sourceAccountId:'',destinationAccountId:'',amount:'',transferredAt:'',notes:''});await Promise.all([crud.load(),loadTransfers()]);crud.setNotice({message:'Transfer completed.'})}catch(err){crud.setNotice({message:errorMessage(err),type:'error'})}finally{setMoving(false)}}
  const active=crud.items.filter(a=>a.active),total=active.reduce((s,a)=>s+Number(a.balance),0)
  if(crud.loading)return <LoadingScreen/>
  return <div className="fade-in"><PageHeader eyebrow="Your money map" title="Accounts" description="See where your money lives and move funds without losing the paper trail." action={()=>start()} actionLabel="Add account"/>
    <Card className="mb-5 overflow-hidden bg-[#122044] text-white"><div className="relative p-6 sm:p-7"><div className="absolute -right-10 -top-16 h-52 w-52 rounded-full bg-blue-500/20 blur-3xl"/><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs text-blue-100/60">Total across active accounts</p><strong className="mt-2 block text-3xl tracking-[-.04em]">{money(total)}</strong><p className="mt-2 text-[11px] text-blue-100/40">{active.length} connected money spaces</p></div><Button onClick={()=>setTransferOpen(true)} className="bg-white text-blue-700 shadow-none hover:bg-blue-50"><ArrowRightLeft size={16}/>Transfer money</Button></div></div></Card>
    {active.length===0?<Card><EmptyState icon={WalletCards} title="Add your first account" message="Start with cash, a bank account, or an e-wallet." action={()=>start()}/></Card>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{active.map(a=><Card key={a.id} className="group relative overflow-hidden p-5"><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full opacity-[.08]" style={{background:a.color}}/><div className="relative flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-2xl text-white shadow-sm" style={{background:a.color}}>{a.type==='BANK'||a.type==='SAVINGS'?<Landmark size={19}/>:a.type==='CASH'?<Wallet size={19}/>:<WalletCards size={19}/>}</span><div className="flex"><button className="icon-button h-8 w-8" onClick={()=>start(a)}><Edit3 size={14}/></button><button className="icon-button h-8 w-8 hover:text-red-500" onClick={()=>crud.remove(a.id)}><Trash2 size={14}/></button></div></div><p className="mt-5 text-xs font-semibold text-slate-500 dark:text-slate-400">{a.name}</p><p className="mt-1 text-2xl font-bold tracking-[-.04em] dark:text-white">{money(a.balance,a.currency)}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-[10px] text-slate-400 dark:border-slate-800"><span>{a.type.replace('_',' ')}</span><span className="flex items-center gap-1 text-emerald-500"><CheckCircle2 size={12}/>Active</span></div></Card>)}</div>}
    <Card className="mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 dark:border-slate-800"><div><h2 className="text-sm font-bold dark:text-white">Transfer history</h2><p className="mt-0.5 text-[11px] text-slate-400">Movements between your own accounts</p></div><button onClick={()=>setTransferOpen(true)} className="text-xs font-semibold text-blue-600">New transfer</button></div>{transfers.length===0?<EmptyState icon={ArrowRightLeft} title="No transfers yet" message="Your account-to-account movements will appear here."/>:<div>{transfers.slice(0,8).map(t=><div key={t.id} className="flex items-center gap-3 border-b border-slate-100 px-5 py-3.5 last:border-0 dark:border-slate-800"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-500/10"><ArrowRight size={16}/></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold dark:text-white">{t.sourceAccount.name} → {t.destinationAccount.name}</p><p className="mt-0.5 text-[10px] text-slate-400">{niceDate(t.transferredAt)}{t.notes?` · ${t.notes}`:''}</p></div><strong className="text-xs dark:text-white">{money(t.amount)}</strong></div>)}</div>}</Card>
    <Modal open={open} onClose={()=>setOpen(false)} title={`${editing?'Edit':'Add'} account`}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field className="sm:col-span-2" label="Account name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Main checking"/><Select label="Account type" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="BANK">Bank account</option><option value="CASH">Cash</option><option value="E_WALLET">E-wallet</option><option value="SAVINGS">Savings</option></Select><Select label="Currency" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option value="PHP">PHP — Philippine peso</option><option value="USD">USD — US dollar</option><option value="EUR">EUR — Euro</option></Select><Field label="Current balance" type="number" min="0" step="0.01" required value={form.balance} onChange={e=>setForm({...form,balance:e.target.value})}/><label><span className="label">Accent color</span><input type="color" className="h-11 w-full rounded-xl border border-slate-200 bg-white p-1.5 dark:border-slate-700 dark:bg-slate-900" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><div className="sm:col-span-2"><FormActions onCancel={()=>setOpen(false)} saving={crud.saving}/></div></form></Modal>
    <Modal open={transferOpen} onClose={()=>setTransferOpen(false)} title="Transfer money" description="Both balances update together, so your total stays accurate."><form onSubmit={submitTransfer} className="space-y-4"><Select label="From account" required value={transfer.sourceAccountId} onChange={e=>setTransfer({...transfer,sourceAccountId:e.target.value})}><option value="">Choose source</option>{active.map(a=><option key={a.id} value={a.id}>{a.name} · {money(a.balance)}</option>)}</Select><div className="mx-auto flex h-9 w-9 items-center justify-center rounded-full bg-blue-50 text-blue-600 dark:bg-blue-500/10"><ArrowDownLeft size={16}/></div><Select label="To account" required value={transfer.destinationAccountId} onChange={e=>setTransfer({...transfer,destinationAccountId:e.target.value})}><option value="">Choose destination</option>{active.filter(a=>String(a.id)!==String(transfer.sourceAccountId)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select><Field label="Amount" type="number" min="0.01" step="0.01" required value={transfer.amount} onChange={e=>setTransfer({...transfer,amount:e.target.value})}/><Textarea label="Notes" value={transfer.notes} onChange={e=>setTransfer({...transfer,notes:e.target.value})} placeholder="Optional transfer note"/><FormActions onCancel={()=>setTransferOpen(false)} saving={moving} label="Complete transfer"/></form></Modal><Toast {...crud.notice} onClose={()=>crud.setNotice(null)}/>
  </div>
}
