import { useEffect, useState } from 'react'
import { Bell, CircleUserRound, Edit3, Moon, Plus, ShieldCheck, Trash2 } from 'lucide-react'
import { api, errorMessage } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import { Button, Card, Field, FormActions, Modal, PageHeader, Select, Toast } from '../components/UI'

export default function SettingsPage(){
  const {user,updateUser}=useAuth();const [form,setForm]=useState({firstName:user.firstName,lastName:user.lastName,phoneNumber:user.phoneNumber||''});const [saving,setSaving]=useState(false);const [notice,setNotice]=useState(null);const [categories,setCategories]=useState([]);const [categoryOpen,setCategoryOpen]=useState(false);const [editing,setEditing]=useState(null);const [category,setCategory]=useState({name:'',type:'EXPENSE',color:'#2F80ED',icon:'circle'})
  const load=()=>api.get('/categories').then(r=>setCategories(r.data));useEffect(()=>{load()},[])
  const saveProfile=async(e)=>{e.preventDefault();setSaving(true);try{const {data}=await api.put('/profile',form);updateUser(data);setNotice({message:'Profile updated.'})}catch(err){setNotice({message:errorMessage(err),type:'error'})}finally{setSaving(false)}}
  const startCategory=(item)=>{setEditing(item||null);setCategory(item?{name:item.name,type:item.type,color:item.color,icon:item.icon}:{name:'',type:'EXPENSE',color:'#2F80ED',icon:'circle'});setCategoryOpen(true)}
  const saveCategory=async(e)=>{e.preventDefault();setSaving(true);try{await api[editing?'put':'post'](`/categories${editing?`/${editing.id}`:''}`,category);await load();setCategoryOpen(false);setNotice({message:'Category saved.'})}catch(err){setNotice({message:errorMessage(err),type:'error'})}finally{setSaving(false)}}
  const removeCategory=async(id)=>{if(!window.confirm('Delete this custom category?'))return;try{await api.delete(`/categories/${id}`);await load()}catch(err){setNotice({message:errorMessage(err),type:'error'})}}
  return <div className="fade-in"><PageHeader eyebrow="Make it yours" title="Profile & settings" description="Keep your identity, preferences, and money categories working the way you do."/>
    <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-5"><Card className="p-6"><div className="flex items-center gap-4"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-500 to-blue-700 text-xl font-bold text-white">{user.firstName?.[0]}{user.lastName?.[0]}</span><div><h2 className="font-bold dark:text-white">{user.firstName} {user.lastName}</h2><p className="mt-1 text-xs text-slate-400">{user.email}</p><span className="mt-2 inline-block rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold uppercase text-emerald-600 dark:bg-emerald-500/10">{user.status}</span></div></div></Card><Card className="divide-y divide-slate-100 overflow-hidden dark:divide-slate-800">{[[Bell,'Notifications','Upcoming bill and budget alerts'],[Moon,'Appearance','Light and dark mode support'],[ShieldCheck,'Security','JWT-protected sessions']].map(([Icon,title,text])=><div key={title} className="flex items-center gap-3 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100 text-slate-500 dark:bg-slate-800"><Icon size={16}/></span><div><p className="text-xs font-semibold dark:text-white">{title}</p><p className="mt-0.5 text-[10px] text-slate-400">{text}</p></div></div>)}</Card></div>
      <Card className="p-5 sm:p-6"><div className="mb-6 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-500/10"><CircleUserRound size={18}/></span><div><h2 className="text-sm font-bold dark:text-white">Personal details</h2><p className="mt-0.5 text-[11px] text-slate-400">The information attached to your workspace</p></div></div><form onSubmit={saveProfile} className="grid gap-4 sm:grid-cols-2"><Field label="First name" required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/><Field label="Last name" required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/><Field className="sm:col-span-2" label="Phone number" value={form.phoneNumber} onChange={e=>setForm({...form,phoneNumber:e.target.value})}/><Field className="sm:col-span-2" label="Email" value={user.email} disabled/><div className="sm:col-span-2"><FormActions onCancel={()=>setForm({firstName:user.firstName,lastName:user.lastName,phoneNumber:user.phoneNumber||''})} saving={saving} label="Save profile"/></div></form></Card>
    </div>
    <Card className="mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 dark:border-slate-800"><div><h2 className="text-sm font-bold dark:text-white">Categories</h2><p className="mt-0.5 text-[11px] text-slate-400">System defaults and your personal categories</p></div><Button variant="secondary" onClick={()=>startCategory()}><Plus size={15}/>New category</Button></div><div className="grid gap-px bg-slate-100 dark:bg-slate-800 sm:grid-cols-2 lg:grid-cols-3">{categories.map(c=><div key={c.id} className="flex items-center gap-3 bg-white p-4 dark:bg-[#151b27]"><span className="h-3 w-3 rounded-full" style={{background:c.color}}/><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold dark:text-white">{c.name}</p><p className="mt-0.5 text-[9px] uppercase tracking-wider text-slate-400">{c.type} · {c.system?'default':'custom'}</p></div>{!c.system&&<><button className="icon-button h-7 w-7" onClick={()=>startCategory(c)}><Edit3 size={13}/></button><button className="icon-button h-7 w-7 hover:text-red-500" onClick={()=>removeCategory(c.id)}><Trash2 size={13}/></button></>}</div>)}</div></Card>
    <Modal open={categoryOpen} onClose={()=>setCategoryOpen(false)} title={`${editing?'Edit':'Create'} category`}><form onSubmit={saveCategory} className="space-y-4"><Field label="Category name" required value={category.name} onChange={e=>setCategory({...category,name:e.target.value})}/><Select label="Type" value={category.type} onChange={e=>setCategory({...category,type:e.target.value})}><option value="EXPENSE">Expense</option><option value="INCOME">Income</option></Select><label className="block"><span className="label">Color</span><input type="color" className="h-11 w-full rounded-xl border border-slate-200 bg-white p-1.5 dark:border-slate-700 dark:bg-slate-900" value={category.color} onChange={e=>setCategory({...category,color:e.target.value})}/></label><FormActions onCancel={()=>setCategoryOpen(false)} saving={saving}/></form></Modal><Toast {...notice} onClose={()=>setNotice(null)}/>
  </div>
}
