import { useState } from 'react'
import { Bell, CircleUserRound, Moon, ShieldCheck } from 'lucide-react'
import { api, errorMessage } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import { Card, Field, FormActions, PageHeader, Toast } from '../components/UI'

export default function SettingsPage(){
  const {user,updateUser}=useAuth();const [form,setForm]=useState({firstName:user.firstName,lastName:user.lastName,phoneNumber:user.phoneNumber||''});const [saving,setSaving]=useState(false);const [notice,setNotice]=useState(null)
  const saveProfile=async(e)=>{e.preventDefault();setSaving(true);try{const {data}=await api.put('/profile',form);updateUser(data);setNotice({message:'Profile updated.'})}catch(err){setNotice({message:errorMessage(err),type:'error'})}finally{setSaving(false)}}
  return <div className="fade-in"><PageHeader eyebrow="Make it yours" title="Profile & settings" description="Keep your identity and preferences working the way you do."/>
    <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-5"><Card className="p-6"><div className="flex items-center gap-4"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-500 to-blue-700 text-xl font-bold text-white">{user.firstName?.[0]}{user.lastName?.[0]}</span><div><h2 className="font-bold dark:text-white">{user.firstName} {user.lastName}</h2><p className="mt-1 text-xs text-slate-400">{user.email}</p><span className="mt-2 inline-block rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold uppercase text-emerald-600 dark:bg-emerald-500/10">{user.status}</span></div></div></Card><Card id="preferences" className="scroll-mt-24 divide-y divide-slate-100 overflow-hidden dark:divide-slate-800">{[[Bell,'Notifications','Upcoming bill and budget alerts'],[Moon,'Appearance','Light and dark mode support'],[ShieldCheck,'Security','JWT-protected sessions']].map(([Icon,title,text])=><div key={title} className="flex items-center gap-3 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100 text-slate-500 dark:bg-slate-800"><Icon size={16}/></span><div><p className="text-xs font-semibold dark:text-white">{title}</p><p className="mt-0.5 text-[10px] text-slate-400">{text}</p></div></div>)}</Card></div>
      <Card id="profile" className="scroll-mt-24 p-5 sm:p-6"><div className="mb-6 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-500/10"><CircleUserRound size={18}/></span><div><h2 className="text-sm font-bold dark:text-white">Personal details</h2><p className="mt-0.5 text-[11px] text-slate-400">The information attached to your workspace</p></div></div><form onSubmit={saveProfile} className="grid gap-4 sm:grid-cols-2"><Field label="First name" required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/><Field label="Last name" required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/><Field className="sm:col-span-2" label="Phone number" value={form.phoneNumber} onChange={e=>setForm({...form,phoneNumber:e.target.value})}/><Field className="sm:col-span-2" label="Email" value={user.email} disabled/><div className="sm:col-span-2"><FormActions onCancel={()=>setForm({firstName:user.firstName,lastName:user.lastName,phoneNumber:user.phoneNumber||''})} saving={saving} label="Save profile"/></div></form></Card>
    </div>
    <Toast {...notice} onClose={()=>setNotice(null)}/>
  </div>
}
